### ISSUE TITLE
Make qc_metrics schema support for both alignment and variant qc

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/argo-metadata-schemas#19]
The current `qc_metrics` schema has some issues when used by `sanger_qc`
1. #/workflow/short_name: short_name is not a valid enum value,
2. #/workflow/inputs/0/analysis_type: sequencing_alignment is not a valid enum value,
3. #/workflow/inputs/1/analysis_type: sequencing_alignment is not a valid enum value,
4. #/experiment: required key [platform] not found,

## Possible Implementation

1. add `short_name` as a valid enum but not required
2. add `sequencing_alignment` as valide enum value
3. add `sequencing_alignment` as valide enum value
4. set `platfomr` as optional not required

**Comment by junjun-zhang** [comment]
All of these can be addressed, but not without caveats. For example, making `platform` optional may make sense for variant calling qc, but it would be good to have it as required for alignment qc.

Anyway, when we make the schema generic to accommodate more different kinds, we will need to accept these drawbacks.

**Comment by junjun-zhang** [comment]
all of these have been addressed in release: [0.3.0](https://github.com/icgc-argo/argo-metadata-schemas/releases/tag/0.3.0). The qc_metrics has been used for both alignment and sanger variant calling
