### ISSUE TITLE
Feature Request: update ES index mapping to sync with dynamic SONG schemas

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/argo-metadata-schemas#32]
## Detailed Description
Dynamic portion of SONG schemas have been changed since last time ES mappings were created.
Here are the changes: https://github.com/icgc-argo/argo-metadata-schemas/compare/0.1.0...0.3.0 (looking for individual schema file for its specific change)

Summary of what need to be sync'd:
* `library_strategy` changed to `experiment_strategy`
*  new field: `variant_class` which should be a root propertity for file_centric mappings. Populate with `null` if SONG metadata does not have it

New fields under `file.info` that are not able to be defined in dynamic SONG schema. See example payloads: [here](https://song.rdpc-qa.cancercollaboratory.org/studies/TEST-PR/analysis/476d777c-c0bf-417d-ad77-7cc0bf117db0) and [here](https://song.rdpc-qa.cancercollaboratory.org/studies/TEST-PR/analysis/3412aba7-b0fc-4fb0-92ab-a7b0fcafb0ab)
* `file.info.data_category` to be added to file_centric mappings as `data_category`
* `file.info.analysis_tools` to be added to file_centric mappings as `analysis_tools`

`data_category` and `analysis_tools` under `file.info` are meant to be the same level as `file.dateType` in SONG, but since we cannot change SONG's base schema, we added them to under info.

So in terms of ES mapping, `data_category` and `analysis_tools` should be added to wherever `data_type` field goes.

**Comment by rosibaj** [comment]
Example schemas:
https://song.rdpc-qa.cancercollaboratory.org/studies/TEST-PR/analysis/476d777c-c0bf-417d-ad77-7cc0bf117db0

https://song.rdpc-qa.cancercollaboratory.org/studies/TEST-PR/analysis/3412aba7-b0fc-4fb0-92ab-a7b0fcafb0ab

**Comment by rosibaj** [comment]
Checking the dev ES docs, i see the first two included already: 
![image](https://user-images.githubusercontent.com/15824252/84047033-d56bc180-a978-11ea-9ed8-1c587bb32e87.png)

but they are not here:
https://github.com/icgc-argo/argo-metadata-schemas/blob/master/mappings/maestro_file_centric.json

**Comment by blabadi** [comment]
The info field in the file should be added in the mapping, also maestro needs to implement that in code since it affects the base schema part in file centric index

**Comment by rosibaj** [comment]
1. thanks @blabadi - I will be setting up this ticket for that feature request: https://github.com/overture-stack/maestro/issues/138.  I will be filling the spec need in there as i learn them.
@junjun-zhang Do you have an example analysis in `rdpc-qa` with `file.info.data_category` that we can use as test data?


2. Here is the PR for the two first mentioned fields: https://github.com/icgc-argo/argo-metadata-schemas/pull/33

**Comment by junjun-zhang** [comment]
@rosibaj the examples already provided: https://github.com/icgc-argo/argo-metadata-schemas/issues/32#issuecomment-640676036

**Comment by rosibaj** [comment]
> @rosibaj the examples already provided: [#32 (comment)](https://github.com/icgc-argo/argo-metadata-schemas/issues/32#issuecomment-640676036)

Apologies; i was confusing these with teh `variant_class` examples.  is there a reason these dont have `variant_class`

**Comment by junjun-zhang** [comment]
`variant_class` is only applicable to `variant_calling` analysisType, the examples above are from `sequencing_alignment`.

Here is an example for variant_calling SONG analysis with `variant_class` populated:  https://song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/29f4806e-8819-41fc-b480-6e8819c1fc19

**Comment by junjun-zhang** [comment]
required updates have been made in ES mappings
