### ISSUE TITLE
Confirm Platform File_Centric Mapping 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-metadata-schemas#43]
We need a  mapping for the elastic-search indices that will be used by the File Repository.  Currently, the indes _only_ contains information directly from Maestro, which means only data found in Song.  

We need to supplement this information with 1) clinical data 2) release information. 

Start from Maestro mapping as an example (https://github.com/icgc-argo/argo-metadata-schemas/blob/master/mappings/maestro_file_centric.json). 

Format the index to include this data: 

- [ ] 1. include all release fields from File Service. These are `file` level field at the top level.  
- `embargo_stage`
- `file_id`
- `labels` object with string keys and array values.. Example:
```
{
  "labels": {
    [key:string]: string[];
  }
}
````
- [ ] 2. Include all file information that originates in an analysis.  Keep the structure of the file as it is now, this point is just for reference. 
- data source for reference is from a song analysis. 
- Example: 
```
curl --location --request GET 'https://song.rdpc-qa.cancercollaboratory.org/studies/TEST-PR/analysis/328ebe1e-28a1-4670-8ebe-1e28a16670d9' \
--header 'Authorization: Bearer 58bb9610-2184-48b2-a189-34016622c0c4'
```
-  [ ] 3. include all current clinical data fields.  Needs to be normalized correctly so talk to @joneubank. 
- from clinical db. 
- currently only "whole program" available from API. We have mentioned we need and API eventually, but basically all teh data that can be submitted. 
- https://clinical.qa.argo.cancercollaboratory.org/api-docs/#/Clinical%20Data/get_clinical_donors 
- dictionary ui showing all clinical data: https://docs.icgc-argo.org/dictionary 
## Expected Outcome 
- A mapping file in the metadata repository that we all agree on!

**Comment by rosibaj** [comment]
Confirmed clinical data: 
- Eventually we want all clinical data available. Kim and Rosi are working on a mockup, that will likely be more donor-centric to explore the data. We realize this is not the first implementation that can be done with clinical data due to only having a file-centric index. 
- As a start, we can uses the fields listed here: (https://projects.invisionapp.com/share/GPZBKMNH3S4#/screens/426403333_FileRepo-Loggedout) from a file-centric view 
-- donor.primary_site
-- donor.vital_status

**Comment by ciaranschutte** [comment]
re: labels @rosibaj advised by @blabadi  that we are only indexing labels we want. Do we need a predefined set to add?

**Comment by ciaranschutte** [comment]
re: release fields. there is a `release_stage` field already. I think this is sufficient for now, there is nothing coded yet.

**Comment by rosibaj** [comment]
@ciaranschutte as of right now, i dont know both the format or exact labels to add as a "redefined" set.

**Comment by rosibaj** [comment]
Flatten the structure to be a more concise as needed for the first pass of this index.

**Comment by rosibaj** [comment]
- Question from Bashar: is this related to the `sample` in any way? 
- @rosibaj will schedule a meeting with @christinayung @samrichca and @joneubank to discuss this

**Comment by samrichca** [comment]
met with rosi and jon earlier and determined fields for mapping
