### ISSUE TITLE
Feature Request - extend Song schemas/experiment, read_groups, files to accommodate the submission of Targeted seq data

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/argo-metadata-schemas#52]
For WXS and Targeted Sequencing data, we would like to add `capture_kit` as optional field under `experiment` in ALL schemas.

**Comment by lindaxiang** [comment]
From the discussion on QC WG meeting, for Exome and targeted sequencing data
Will need to require the user to provide the capture kit as part of submission
- Submit capture kit or bed file?
- Have a few defaults, also let them submit bed file if it’s different

**Comment by puneet-oicr** [comment]
Linda to update ticket details

**Comment by lindaxiang** [comment]
Proposed changes to `experiment` table have been reviewed and approved by DCMWG (May 31st, 2023), will continue to implement the changes in the schema.

**Comment by lindaxiang** [comment]
addressed by PR: https://github.com/icgc-argo/argo-metadata-schemas/pull/73
the updated schema has applied to Prod, QA and Dev.
