### ISSUE TITLE
🐛 Typo in metaschema resulting in improperly passed param🐛 

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/argo-metadata-schemas#69]
## Describe the bug
Typo of `allof` instead of `allOf` results in all experiment info being unvalidated.

## Steps To Reproduce
Get Schema and example payload. Payload silently validates currently
![image](https://github.com/icgc-argo/argo-metadata-schemas/assets/22638361/a7bc98f5-64d2-471e-9eec-328375a660c6)
Current payload has `Illumina` when value should be `ILLUMINA`
![image](https://github.com/icgc-argo/argo-metadata-schemas/assets/22638361/b041c1f5-b71b-42a8-815d-5ae6b03a3eb0)

Looking at schema, note `allof`:
![image](https://github.com/icgc-argo/argo-metadata-schemas/assets/22638361/dc6a491d-8f55-4542-9ad0-dfeef73c9cf3)

Correcting typo results in proper enforcement of schema
![image](https://github.com/icgc-argo/argo-metadata-schemas/assets/22638361/008285cb-8fb3-4256-a7ea-d0f77d6670f8)

## Expected behaviour
Schema should catch invalid enum values

**Comment by lindaxiang** [comment]
Addressed by PR: https://github.com/icgc-argo/argo-metadata-schemas/pull/70

**Comment by puneet-oicr** [comment]
Fix applied to prod
