### ISSUE TITLE
related schema changes for targeted-seq and wxs

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/argo-metadata-schemas#75]
Other than sequencing_experiment, the following schemas will also need to be updated to reflect the changes for targeted-seq and wxs if applicable. 
- sequencing_alignment
- qc_metrics
- variant_calling
- variant_calling_supplement
- variant_processing
- splice_junctions
- supplement

**Comment by edsu7** [comment]
Waiting for SONG schema audit and waiting for data from MONSTAR incase any supporting changes are needed

**Comment by lindaxiang** [comment]
PR: https://github.com/icgc-argo/argo-metadata-schemas/pull/79

**Comment by lindaxiang** [comment]
New version of schema: https://github.com/icgc-argo/argo-metadata-schemas/releases/tag/0.9.0 has been released and applied to Prod, QA and Dev. 
Closing the ticket.
